### PR TITLE
Minor fixes for Spanish translation and Feedback email Intent

### PR DESCRIPTION
**Pull request by martarodriguezm**
Hi,
I wanted to use your library for one of my projects and I have realised that the Spanish translations needed some fixes (I'm from Spain).
On the other hand, the feedback email intent didn't work in Android 7, so I fixed using Intent.ACTION_SENDTO so the user can choose their favorite mail client, this fixes the issue #81.

Thanks,
Marta

### CODE REVIEW

**Review by IndiaVenom — APPROVED** [review]

**Comment by pocho23** [comment]
👍

**Comment by palVikas9** [comment]
Hi marta,

Can you please tell me how to add the fixed version to my application. The gradle inclusion does not update the code to fix feedback email intent.

**Comment by martarodriguezm** [comment]
Hi @palVikas9,

I'm not the owner of this repository, I just contributed with this pull request. I think that they have merged it but they haven't updated the gradle version.
Perhaps @pocho23 or @IndiaVenom can create a new version with my fixes and upload it to maven central.

Regards,
Marta

**Comment by palVikas9** [comment]
Hi @marta-rodriguez 

Thanks for contributing to the repository with the fixes. Maybe , I should ask @pocho23 or @IndiaVenom   to add it the maven central so that it can be used by everyone with the fixes. 

It's an awesome library to get user feedback without getting bad reviews.

Regards, 
Vikas

**Pull request merged**
